# This is a workflow to publish new package on npm after github release

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  release:
    types: [published]

jobs:
  publish:
    name: Write release notes
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    # additional if condition: compare tag with package.json version
    # - name: Get the version
    # id: get_version
    # run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    # --> solution from https://github.community/t5/GitHub-Actions/How-to-get-just-the-tag-name/td-p/31595
    steps:
      - if: "github.event.release.prerelease"
        uses: lakto/gren-action@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - if: "!github.event.release.prerelease"
        uses: lakto/gren-action@v2.0.0
        with:
          options: ' --override'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
