name: Main CI/CD
env:
  nv: 16.17.0

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  release:
    types: [ published ]

jobs:
  # code linter
  lint:
    name: Run lint
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.nv }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nv }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run the lint scripts
        run: yarn lint-ci

  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.nv }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nv }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build the app
        run: yarn build-prod

  # Automate releases with Conventional Commit Messages as Pull Requests are merged into "main" branch
  release-please:
    name: Prepare next release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.ref != 'refs/heads/deploy'
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Run release please
        uses: GoogleCloudPlatform/release-please-action@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          release-type: node
          package-name: 365-photo-project
          # prerelease: true
          changelog-types: '[
              {"type": "feat", "section": "Enhancements", "hidden": false },
              {"type": "fix", "section": "Bug Fixes", "hidden": false },
              {"type": "chore", "section": "Maintenance", "hidden": false },
              {"type": "refactor", "section": "Maintenance", "hidden": false },
              {"type": "style", "section": "Maintenance", "hidden": false },
              {"type": "docs", "section": "Documentation", "hidden": false }
            ]'

  # deploy and publish; runs on release only
  publish:
    name: Publish
    needs: [
      lint,
      build
    ]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Set up Node.js ${{ env.nv }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nv }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn deploy
