name: Main CI/CD
env:
  nv: 16.17.0

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.nv }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nv }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build the app
        run: yarn build

  publish:
    name: Write release notes
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ env.nv }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.nv }}
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build the app
        run: yarn build
      - if: 'github.event.release.prerelease'
        uses: lakto/gren-action@v2.0.0
        with:
          options: '--override --prerelease'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - if: '!github.event.release.prerelease'
        uses: lakto/gren-action@v2.0.0
        with:
          options: '--override'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
