name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build

  publish:
    name: Write release notes
    needs: [build]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - if: "github.event.release.prerelease"
        uses: lakto/gren-action@v2.0.0
        with:
          options: '--override --prerelease'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - if: "!github.event.release.prerelease"
        uses: lakto/gren-action@v2.0.0
        with:
          options: '--override'
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
